### ISSUE TITLE
No rule to make target 'Xmr_WALLET_LIBRARY-NOTFOUND'

### ISSUE THREAD

**Issue by SergeyAnkarenko** [moneroexamples/openmonero#101]
I am getting No rule to make target 'Xmr_WALLET_LIBRARY-NOTFOUND' when building openmonero
I have tried the both 'new_monero' and 'use_blocks_range' branches

![screenshot from 2018-10-17 23-22-03](https://user-images.githubusercontent.com/6827668/47114097-8c2aa380-d263-11e8-94a2-38fd31adedfb.png)

Ubuntu 18.04
Monero 0.13.0

**Comment by moneroexamples** [comment]
Build procedure changed for monero. Please have a look here: https://github.com/moneroexamples/onion-monero-blockchain-explorer#compilation-on-ubuntu-16041804 

Basically need to use `USE_SINGLE_BUILDDIR=1 make` instead of just `make`. So you have delete your monero build folder, and rebuild it with that flag.

`use_blocks_range` is the current devel branch. no need to recheck with new_monero. I will remove that branch soon.

p.s.
openmonero will not work properly after the v9 fork. It has not been adjusted to it yet, though it should compile with new monero codebase.

**Comment by SergeyAnkarenko** [comment]
Thank you very much!

After v9 fork openmonero won't work completely or some API methods will still work?
What should be changed to make openmonero to work properly?

**Comment by moneroexamples** [comment]
Making txs will not work, as BulletProofs will be mandatory. At present OpenMonero still uses RingCT. Once MyMonero.com upgrades to BulletProofs, I will update OpenMonero respectively. 

But if you have any other issues, please don't hesitate letting me know.

**Comment by SergeyAnkarenko** [comment]
I understand, thanks
