### ISSUE TITLE
incorrectly processing one transaction

### ISSUE THREAD

**Issue by TheTrunk** [moneroexamples/openmonero#145]
Hello, 
I have a problem with only one transaction that is not getting correctly proccessed.

In OpenMonero output the error is shown as following
```
2019-04-20 07:52:01,604 [I,OM,TxSearch.cpp:virtual void xmreg::TxSearch::operator()():297] 49B2it: found some outputs in block 1813548, tx: e04b27c1d2350e6c641dc44d6ec9c70ce07b1763a1f709729669001b90acbf34
# ERR: SQLException in /root/openmonero/src/db/MySqlAccounts.cpp(insert) on line 334
# ERR: Duplicate entry '9d6a508d9500ac97167ebab5e7a5e2e2fc044a77df3d56bef4e8efd0595734d8' for key 'out_pub_key'
2019-04-20 07:52:01,635 [E,OM,TxSearch.cpp:virtual void xmreg::TxSearch::operator()():632] 49B2it: exception in TxSearch: no_rows_inserted is zero!
```
I also tried to decode the transaction on my explorer https://explorer.xmr.zelcore.io/search?value=e04b27c1d2350e6c641dc44d6ec9c70ce07b1763a1f709729669001b90acbf34
and it is giving following error
```
Error: invalid rct amount
```
Decoding on other explorer works correctly. I am running the latest version of openmonero master, onion explorer and monero 0.14.0.2.
I tried rescanning the address in openmonero firstly. Then when I realised that the error is on the explorer as well I resynced monero blockchain from scratch on backup server and put this newly synced data on main server but still the same error persists.

**Comment by moneroexamples** [comment]
So only this one tx cause issues for both the explorer and openmonero? 

The openmonero fails to insert found output `out_pub_key` of value `9d6a508d9500ac97167ebab5e7a5e2e2fc044a77df3d56bef4e8efd0595734d8` into `Outputs` table in its mysql/mariadb, due to already one being there. Outputs should be unique. One thing you can do is to go to mysql/mariadb and inspect `Outputs` table and check if the output in question is already actually there and to which account and transaction it belongs to (if you use `phpmyadmin` its straight forward to inspect the table). Is it the same account/tx you are scanning when the error occurs? 

The issue with explorer is more mysterious. Using which explorer decoding was successful? Maybe the other explorer (assuming its also the onion explorer) was using its `devel` branch instead of `master`: https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/devel ? This would mean that current development version of monero was used as well in that case.

**Comment by TheTrunk** [comment]
Yes this is the only transaction that is causing issues.

I see it in my mysql database correctly assigned - all accounts, transactions and outputs is correct. Should I try removing those rows? (removing entire account and importing it back)

I can decode the transaction basically on any other explorer such as the first listed in Readme - https://xmrchain.net/

I will setup another explorers using different branches (devel, current master) to see how it behaves.

**Comment by moneroexamples** [comment]
> removing entire account and importing it back

Yes, this is what I would try and see how it goes. For some reason the output in question is already present in the db, or its gets added twice.

**Comment by TheTrunk** [comment]
Thank you,
Indeed removing the account form database and rescanning solved the issue.

As far as explorer goes, newly compiled master branch gives the same error. I tried devel branch - compilation required master branch of monero (instead of 0.13 release branch), which I compiled and thus onion compiled successfully. But upon running gives error 
```
 MDB_VERSION_MISMATCH: Database environment version mismatch
```
So I would probably need to run the built master of Monero instead of using the prebuilt 0.14.0.2 binary - that may cause a downtime if the database will be updating so I will  try that on some backup server later.
