### ISSUE TITLE
Single Database with Multiple OpenMonero Clients

### ISSUE THREAD

**Issue by skubakdj** [moneroexamples/openmonero#159]
I noticed in [this comment ](https://github.com/moneroexamples/openmonero/issues/157#issuecomment-507171782) it was recommended against pointing multiple instances of OpenMonero to the same database. The possible problems seem to be (1) different machines could have search threads running for the same account, and (2) search threads "thinking" there are duplicates in data. 

I've been experimenting with a middleware to solve (1) so there's never duplicate search threads running across machines. What approaches could solve for (2) and are there any other possible pitfalls with a shared database setup?

**Comment by moneroexamples** [comment]
> so there's never duplicate search threads running across machines

If you can ensure that no duplicate threads are running, then the second issue of "search threads "thinking" there are duplicates in data" shouldn't be a problem. The reason is that only one account will be active at any given time.

To make it more robust changes to TxSearch would be required though. For example here: 

https://github.com/moneroexamples/openmonero/blob/57bd8d523b4748d6dbd8a5de2cf3768c238e87f0/src/TxSearch.cpp#L389-L399

In this example, if outputs insertion fails, e.g., due to there being already existing one in db, the TxSearch thread will throw an exception and terminate. To mitigate this, instead of throwing the exception, you could `continue`  scanning next transaction in line instead.

**Comment by skubakdj** [comment]
Thanks for the info @moneroexamples! I'll continue to test and will look into making the robustness improvements if we run into issues.
