### ISSUE TITLE
When to use `generated_locally` in a `login` request?

### ISSUE THREAD

**Issue by skubakdj** [moneroexamples/openmonero#160]
I've noticed there's a good bit of difference in how a `login` request is handled based on the value of `generated_locally`. 

For example, if `generated_locally` is set to `false`, scanning will automatically begin at block 0 without any additional requests. If set to `true`, scanning will begin at the current height of the chain.

What does `generated_locally` mean and when should it be set? My apologies if this is already documented somewhere, I searched through the readme/source and couldn't find an answer.

**Comment by paulshapiro** [comment]
Did you check the Monero meta spec for our shared API format?

**Comment by paulshapiro** [comment]
It's used as an initial intermediary flag to be storable by the server as to the import requirements of an Account.

**Comment by moneroexamples** [comment]
As @paulshapiro said. Also `generated_locally` is set to `true` when you create new account. For such TxSearch scanning will start from the timestamp/blockheight of the time when the account has been created. It is assumed in this case that such wallet is totally new, and has no previous txs which wound require rescanning blockchain.

When you import existing account,  `generated_locally` is set to `false` to indicate that this account may have existing transactions. In such a case a prompt is produced asking the user to import wallet. This will happen when import fee is not zero. In your case, scanning starts automatically from block zero, because import fee is set to zero, so the wallet does not ask for anything. 

You can modify import fee as well as wallet addresses to receive the fee here: 

https://github.com/moneroexamples/openmonero/blob/master/config/config.json#L37

**Comment by skubakdj** [comment]
I didn't check through the spec, but will do so next time. Thank you both for the explanations @paulshapiro and @moneroexamples!
