### ISSUE TITLE
get_unspent_outs required arguments

### ISSUE THREAD

**Issue by Jaqueeee** [moneroexamples/openmonero#32]
Noticed OpenMonero requires the parameters "mixin", "use_dust" and "dust_threshold" while MyMonero doesn't. Skimmed through the code and could see that mixin and use_dust parameters were used. Am I missing something?

**Comment by moneroexamples** [comment]
From my old notes about mymonero's api. The frontend used to send these parameters in the request. 
```
// get_unspent_outs input
{
  "address":"address dddd",
  "view_key":"viewkey gggg",
  "amount":"0",
  "mixin":3,
  "use_dust":false,
  "dust_threshold":"1000000000"
}
```
Guess it changed since last year. This is not a problem, I can remove them. They are not used anyway, except dust_threshold. 

dush_treshold is used here: https://github.com/moneroexamples/openmonero/blob/master/src/YourMoneroRequests.cpp#L510

And it is used to so that we do not send outputs smaller that this threshold (0.001) to the frontend when constructing txs. This can also be removed if needed.

**Comment by moneroexamples** [comment]
I checked now, and see that mymonero still sends such a request to the backend. Check this js file:

https://mymonero.com/js/controllers/send_coins.js?1

```
            var getUnspentOutsRequest = {
                address: AccountService.getAddress(),
                view_key: AccountService.getViewKey(),
                amount: '0',
                mixin: mixin,
                // Use dust outputs only when we are using no mixins
                use_dust: mixin === 0,
                dust_threshold: config.dustThreshold.toString()
            };
```

**Comment by Jaqueeee** [comment]
OK. thanks. Added those parameters to https://github.com/monero-project/monero/pull/2109 now.
