### ISSUE TITLE
Making openmonero work for electroneum

### ISSUE THREAD

**Issue by luckytaken** [moneroexamples/openmonero#70]
I was trying to set up openmonero for electroneum, but electroneum doesn't have RingCT, is there anyway I could disable RingCT for the use of openmonero with electroneum's blockchain? 

Thanks a lot!

**Comment by moneroexamples** [comment]
Unfortunately there is no any flag or option to disable it. The relevant part would need to be rewritten in the backend's C++ code.

**Comment by luckytaken** [comment]
Is there a particular commit I can revert back to ?

**Comment by moneroexamples** [comment]
Not really. Development of openmonero started at around the time ringct was being introduced, and since then a lot has changed. The earliest version of openmonero simply did not work at the time. This is also the reason why there is no openmonero for aeon which is close to monero in terms of its source code.

**Comment by luckytaken** [comment]
Ah okay
