### ISSUE TITLE
Unsigned long

### ISSUE THREAD

**Issue by eugeneives** [moneroexamples/openmonero#76]
Hello! Im Eugene from Guarda Wallet. We want to support XMR in our wallet using openmonero. We have configured the sending of transactions, all is well! But we can not import a third-party address. While the import status is live (Payment not yet received >>> Wallet already imported or in the progress). Import did not happen after 30 hours. How can we check this? Server log?

**Comment by moneroexamples** [comment]
openmonero is still work in progress, so number of functions/features can still be missing or/and be broken, not optimised or tested. Importing accounts is one of the things that still needs to be worked on. But anyway, the import account info is stored in `Payments` table in mysql. You see the error you get because this table probably already contains information about the account you are importing. To solve this you have to manually delete the row in that table which contains the address you are importing, and try re-importing said account again.

**Comment by eugeneives** [comment]
@moneroexamples we have some errors again
*boost::system::error_code const&, unsigned long*

**Comment by moneroexamples** [comment]
Which branch do you use? master or latest https://github.com/moneroexamples/openmonero/tree/sending_to_subaddress

Also any more details abou this error? which line, function, or when it occurs?

**Comment by moneroexamples** [comment]
Closing due to luck of feedback.
