### ISSUE TITLE
Fail to check ringct signature 

### ISSUE THREAD

**Issue by RomyToklio** [moneroexamples/openmonero#87]
Hi, we got an error on submt_raw_tx request. Request return  ´Reason not given by daemon. A guess is 'Failed to check ringct signatures‘. Did you know where it could came from ? 
Thank you ;)

**Comment by moneroexamples** [comment]
Which branch of openmonero do you use? Master or its current devel branch (use_blocks_range)? 

Which monero version (current monero master branch or official release version, e.g. 0.12.2.0) and network (testnet,  stagnet)? 

Does the problem occur for all txs you try to make, or just one or two sometimes?

**Comment by RomyToklio** [comment]
We are using current monero master branch and master openmonero. I try devel  branch but when openmonero start it show a wrong blockchain height.

Thank you for you response

**Comment by moneroexamples** [comment]
Current openmonero master branch wont even compile with current monero master branch. You must be using something else, maybe 0.12.0.0 release version of monero?. 

Anyway, the last time your issues occurred was because key images were not sorted in a tx. It should be fixed, thus maybe something new is happening. We can check this using raw tx data that is submitted. When openmonero creates a tx, before it submits it to the daemon, it provides confirmation window with raw tx data in hex. Would you mind posting example of such tx data? This would enable checking sorting of the key images. Also I could attempt manually submit it to the monero network and inspect why daemon is rejecting it. Also need to specify which monero network (testned, stagenet or mainnet) if you provide raw tx data in hex. 

 > I try devel branch but when openmonero start it show a wrong blockchain height. 

Could you give more details about that. Also to clarify,  you are taking about this branch of openmonero?: https://github.com/moneroexamples/openmonero/tree/use_blocks_range

**Comment by moneroexamples** [comment]
Since no updates, I guess the issue can be closed?
