### ISSUE TITLE
[Discussion] Any plans for WebSockets?

### ISSUE THREAD

**Issue by 0xA01** [moneroexamples/openmonero#95]
Hie. Just want to thank you for great project once again :) and ask how about WebSockets? I read somewhere you planning to move to WS PUSH API instead of REST PULL or it was my dream? I'm asking because I'd like to help on this.

**Comment by 0xA01** [comment]
Hey @moneroexamples few more questions if you don't mind.

I'm not enemy of MySQL but why do you use it? And what exactly it caching talking about `Outputs` for example: only known accounts outputs or whole chain? Because DB is massive enough. I have few thoughts on it to try to port it to something more modern maybe some column DB or even do not persist this cache if scanning will be fast enough. I meant: If somebody using Light wallet only once a life, do we need to store his outputs forever? And another question: is currently DB scheme shard-ready (split to several instances in case of being-too-large)?

Thanks for your time.

**Comment by moneroexamples** [comment]
> I'm not enemy of MySQL but why do you use it? 

I use it because it was easiest for me to use (phpmyadmin is also useful). I'm not db expert so I chose what I felt conformable with and had C++ support.. P.S. I think MyMonero is also powered by MySql.

> And what exactly it caching talking about Outputs for example: only known accounts outputs or whole chain? 

Outputs of the accounts only. 

> Because DB is massive enough. I have few thoughts on it to try to port it to something more modern maybe some column DB or even do not persist this cache if scanning will be fast enough. 

Yep, if you can do it, why not. Even optimization of current MySql layout would be good start. Maybe some better datatypes for what it uses now, some sql views, better queries, mysql functions? Don't really know what modern mysql is capable of. 

>I meant: If somebody using Light wallet only once a life, do we need to store his outputs forever? 

If you delete accounts details from the database you would have to rescan blockchain again if a users logs back. Its not possible to get accounts outputs and inputs of an addresses without going through every single txs in blockchain.

Before I already had idea to add an ability so that a user can remove all its data from openmonero database. https://github.com/moneroexamples/openmonero/issues/46 . But haven't gotten into implementing it. This could be useful for privacy reasons (a user don't want his/hers wallet info to be stored in open monero anymore), and removing some pressure from database.

> And another question: is currently DB scheme shard-ready (split to several instances in case of being-too-large)?

No. Current DB design is as simple as I could make it. Thus probably there is plenty of room for improvements and optimizations. If you have ideas and know how can the DB be improved, it would be most welcomed.

**Comment by 0xA01** [comment]
@moneroexamples I appreciate your participation but how about following experimental architecture I'm going to implement:

1) in front of user`s requests we use nginx or event double layer pass nginx -> haproxy (dont ask me why but sometime you need second layer but still gathering everything with nginx)

2) proxy pass implements some shard technique for example it just doing
```
hash(public_key) // do we know public key or may knew public_key on every request?
```
3) selecting one of
```
servers = [
  "0.0.0.0",
  "1.1.1.1",
  "2.2.2.2"
  // ...
]
```
based on `hash(public_key)[0]`
4) backends count may grew on decrease this is the reason to do not persist data as we even may need broadcast invalidation event
5) tell me your thoughts on this

*yours respectfully*

**Comment by 0xA01** [comment]
I meant if we use < 10 servers to use % and only latest letter of hash for example, tell me if was clear or not. For 20 servers we will need two letters and so on.

**Comment by 0xA01** [comment]
> If there are multiple servers, would it mean that that there would be multiple, independent mysql databases?
 
Yes all workers are independent

>  In that case some sort of mechanism should be in place to tell when one server is down and users from that server are forced to connect to a different one, so that e.g., they don't have to pay for importing all their txs on the new server

nginx round-robing doing this

OK I will try to bing some code in near few weeks and we will back to this discussion. Closing for now. Thanks for answers once more time!

**Comment by moneroexamples** [comment]
No problem, and let me know if you have further questions or something.
